/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import building_number from './building_number';
import city_name from './city_name';
import city_pattern from './city_pattern';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import country from './country';
import full_address from './full_address';
import postcode from './postcode';
import state from './state';
import street_name from './street_name';
import street_pattern from './street_pattern';

const location: LocationDefinition = {
  building_number,
  city_name,
  city_pattern,
  city_prefix,
  city_suffix,
  country,
  full_address,
  postcode,
  state,
  street_name,
  street_pattern,
};

export default location;
